import 'package:flutter/material.dart';

class CmkColors {
  static ThemeData get theme => themeData(ThemeData(primarySwatch: CmkColors.blue));

  static ThemeData get darkTheme => themeData(ThemeData.dark());

  static bool isDark(ThemeData themeData) => themeData.brightness == Brightness.dark;

  static ThemeData themeData(ThemeData base) => base.copyWith(
        accentColor: CmkColors.blueAccent,
        secondaryHeaderColor: CmkColors.blue[isDark(base) ? 800 : 300],
        cardTheme: CardTheme(
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
        chipTheme: ChipThemeData.fromDefaults(
          primaryColor: isDark(base) ? CmkColors.blueAccent : CmkColors.blue,
          secondaryColor: CmkColors.purple,
          labelStyle: base.textTheme.bodyText1!,
        ),
        buttonTheme: ButtonThemeData(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          buttonColor: CmkColors.blue,
          textTheme: ButtonTextTheme.primary,
        ),
      );

  //Pallet Gen: http://mcg.mbitson.com/#!?blue=%23115d80&themename=couriermarket
  // --- START AUTOGENERATED CODE ---
  static const MaterialColor blue = MaterialColor(_bluePrimaryValue, <int, Color>{
    50: Color(0xFFA7DBF3),
    100: Color(0xFF63C0EA),
    200: Color(0xFF32ACE4),
    300: Color(0xFF1884B6),
    400: Color(0xFF15719B),
    500: Color(_bluePrimaryValue),
    600: Color(0xFF0D4965),
    700: Color(0xFF0A364A),
    800: Color(0xFF06222F),
    900: Color(0xFF030E14),
  });
  static const int _bluePrimaryValue = 0xFF115D80;

  static const MaterialColor blueAccent = MaterialColor(_blueAccentValue, <int, Color>{
    100: Color(0xFF91DCFF),
    200: Color(_blueAccentValue),
    400: Color(0xFF0883BC),
    700: Color(0xFF106F9B),
  });
  static const int _blueAccentValue = 0xFF2BBCFF;

  static const MaterialColor purple = MaterialColor(_purplePrimaryValue, <int, Color>{
    50: Color(0xFF8FACDE),
    100: Color(0xFF5581CC),
    200: Color(0xFF3664B3),
    300: Color(0xFF25457C),
    400: Color(0xFF1E3865),
    500: Color(_purplePrimaryValue),
    600: Color(0xFF101E35),
    700: Color(0xFF09111E),
    800: Color(0xFF020406),
    900: Color(0xFF000000),
  });
  static const int _purplePrimaryValue = 0xFF172B4D;

  static const MaterialColor purpleAccent = MaterialColor(_purpleAccentValue, <int, Color>{
    100: Color(0xFF70A1F3),
    200: Color(_purpleAccentValue),
    400: Color(0xFF173E80),
    700: Color(0xFF1A3564),
  });
  static const int _purpleAccentValue = 0xFF1463E9;
// --- END AUTOGENERATED CODE ---
}
