# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Bootstrap the sdk"
  lane :bootstrap do
    #xcode_select "/Applications/Xcode_11.3.1.app"
    flutter_bootstrap(flutter_channel: 'beta')
    flutter_generate()
  end

  desc "Build to app distribution"
  lane :alpha do
    bootstrap
    flutter_build(build_args: %w[--release --no-codesign --target lib/main_stage.dart])
    gym(silent: true, suppress_xcode_output: true)
  end

  desc "Build to apple tf"
  lane :beta do
    bootstrap
    flutter_build(build_args: %w[--release --no-codesign --target lib/main.dart])
    gym(silent: true, suppress_xcode_output: true)
  end

  desc "Build to apple ga"
  lane :release do
    bootstrap
    flutter_build(build_args: %w[--release --no-codesign --target lib/main.dart])
    gym(silent: true, suppress_xcode_output: true)
  end
end

platform :android do
  desc "Bootstrap the sdk"
  lane :bootstrap do
    flutter_bootstrap(
        flutter_channel: 'beta',
        android_licenses: {},
    )
    flutter_generate()
  end

  desc "Build to app distribution"
  lane :alpha do
    bootstrap
    flutter_build(build_args: %w[--release --shrink --target lib/main_stage.dart])
  end

  desc "Build to play beta"
  lane :beta do
    bootstrap
    flutter_build(build_args: %w[--release --shrink --target lib/main.dart])
    # upload_to_play_store
  end

  desc "Build to play ga"
  lane :release do
    bootstrap
    flutter_build(build_args: %w[--release --shrink --target lib/main.dart])
    # upload_to_play_store
  end
end
